[build]
  command = "yarn build"
  publish = "dist"

[template.environment]
  VUE_APP_CT_PROJECT_KEY = "Your project key (optional)"
  VUE_APP_CT_CLIENT_ID = "Your client ID (optional)"
  VUE_APP_CT_CLIENT_SECRET = "Your client secret (optional)"
  VUE_APP_CT_SCOPE = "Your client scope (optional)"
  VUE_APP_CT_AUTH_HOST = "Auth host (default Europe)"
  VUE_APP_CT_API_HOST = "API host (default Europe)"
  YARN_FLAGS = "--no-ignore-optional"

# Rule for router history mode
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
