version: 2

jobs:
  build:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/base:12
        environment:
          JEST_JUNIT_OUTPUT: test-results/unit/output.xml

    working_directory: ~/sunrise-spa
    # docker image cypress/base:10 is broken yarn install --frozen-lockfile
    # ends up with error: The engine "node" is incompatible with this module.
    # tried updating yarn but failed so using npm now
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v6-deps
      # - run:
      #     name: Get latest yarn version
      #     command: apt-get upgrade yarn -y
      - run:
          name: Show versions
          command: yarn -v && node -v
      - run:
          name: Install dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Run Unit tests
          command: yarn test:unit --ci --reporters=default --reporters=jest-junit --no-cache
      # cannot use reporter after update:
      #    https://github.com/cypress-io/cypress/issues/4304
      - run:
          name: Run E2E tests
          # command: yarn test:e2e --headless --reporter mocha-multi-reporters
          command: yarn test:e2e --headless
      - store_artifacts:
          name: Store E2E videos
          path: tests/e2e/videos
      - store_artifacts:
          name: Store E2E screenshots
          path: tests/e2e/screenshots

      - store_test_results:
          path: test-results